#!/bin/bash
ARCHIVE_DIR=/backups
DATE_VAR=$(date | awk '{print $1, $2, $3, $4}' | sed 's/ /_/g')
#usage function
usage(){
	echo 'My back up tool' >&2
	echo 'Just uses /home and sends it to /backups if it exists, if not then creates' >&2
}
usage
#check if root(must be root)
if [[ "${UID}" -ne 0 ]]
then
	echo 'Sorry you are not root, try again using sudo' >&2
	exit 1
fi
#check if dir exists
if [[ -d  "${ARCHIVE_DIR}" ]]
then
	echo 'Lets go check if folder exists and create if does not'
	mkdir -p "${ARCHIVE_DIR}"
	if [[ "${?}" -ne 0 ]]
	then
		echo 'something went wrong' >&2

	fi 
fi
HOME_DIR="/home/${USERNAME}"
ARCHIVE_FILE="${ARCHIVE_DIR}/${USERNAME}"
if [[ -d "${HOME_DIR}" ]]
then
	echo "Archiving ${HOME_DIR} to ${ARCHIVE_FILE}"
	tar -zvcf ${ARCHIVE_FILE}' '${DATE_VAR} ${HOME_DIR} &> archive_log.txt
	if [[ "${?}" != 0 ]]
	then
		echo "Cant create backup for ${USERNAME}" >&2
		exit 1

	fi
fi
chmod 111 /backups
